_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
name: 'Independent Panel Truth Recovery NI'
mail: test@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
uuid: 7b524741-f6b5-4550-86a9-535a9b0aa66b
frontpage_title: 'Welcome to Drupal site'
