_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
name: 'Civil Service Commissioners for Northern Ireland'
mail: test@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
uuid: 0f652bed-edfc-491a-ae0e-327f97e5baef
frontpage_title: 'Welcome to Drupal site'
