project_type: unity
project_name: 'Unity Svr 3'
project_id: platprojidxxxxx
project_disk_size: 4000
db_disk_size: 2000
sites:
    pacni:
        name: 'Planning Appeals Commission'
        url: pacni.gov.uk
        solr: pacni
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/pacni ; drush core-cron'
        database: pacni
        status: development
        default: false
    judiciaryni:
        name: 'Judiciary NI'
        url: judiciaryni.uk
        solr: judiciaryni
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/judiciaryni ; drush core-cron'
        database: judiciaryni
        status: development
        default: false
