_core:
  default_config_hash: bDFGUgtLFi78q8mKcex_zI95jAXkkm_alGhixx2giXA
langcode: en-gb
mirror_operations:
  'view scheduled transition': update
  'add scheduled transition': update
  'reschedule scheduled transitions': update
automation:
  cron_create_queue_items: true
bundles:
  -
    entity_type: node
    bundle: basic_page
  -
    entity_type: node
    bundle: blog
  -
    entity_type: node
    bundle: bulk_pledges
  -
    entity_type: node
    bundle: event
  -
    entity_type: node
    bundle: faq
  -
    entity_type: node
    bundle: feature
  -
    entity_type: node
    bundle: first_name
  -
    entity_type: node
    bundle: form_page
  -
    entity_type: node
    bundle: forum
  -
    entity_type: node
    bundle: news
  -
    entity_type: node
    bundle: newsletter
  -
    entity_type: node
    bundle: organisation
  -
    entity_type: node
    bundle: panel
  -
    entity_type: node
    bundle: phrase_of_the_week
  -
    entity_type: node
    bundle: podcast
  -
    entity_type: node
    bundle: shared_heritage
  -
    entity_type: node
    bundle: surname
  -
    entity_type: node
    bundle: training_course
  -
    entity_type: node
    bundle: webform
message_transition_latest: 'Scheduled transition: transitioning latest revision from [scheduled-transitions:from-state] to [scheduled-transitions:to-state]'
message_transition_historical: 'Scheduled transition: copied revision #[scheduled-transitions:from-revision-id] and changed from [scheduled-transitions:from-state] to [scheduled-transitions:to-state]'
message_transition_copy_latest_draft: 'Scheduled transition: reverted [scheduled-transitions:latest-state] revision #[scheduled-transitions:latest-revision-id] back to top'
message_override: false
